### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by kjm0001** [enterprisemodules/connect#3]
Very interested in using the connect the module. When clicking on the links in the Beginning with connect module section, they are all invalid. Wold like to see on how to setup and use, thanks.

**Comment by hajee** [comment]
The links where still to the old location. Fixed this in d662520eef13d88ac67472c959e90fbccd075a84. Now you should be able to click on the documentation links and get some documentation.

**Comment by kjm0001** [comment]
thank you
