### ISSUE TITLE
Error when attempting to create an array of hashes

### ISSUE THREAD

**Issue by joenuts1** [enterprisemodules/connect#6]
```
Ubuntu 16.04
Puppet 3.8.5
Hiera 3.1.2
Ruby 2.3.0
==
hiera.yaml
:backends:
  - connect
:connect:
  :datadir: "/etc/puppet/connectdata"
:hierarchy:
  - common
==
/etc/puppet/connectdata/common.config
hash_one = {
    "type" => "group",
    "filter" => ""
}

hash_two = {
    "type" => "passwd",
    "filter" => ""
}

test::parameter = [
    hash_one,
    hash_two
]

==
test.pp
class test(
  $parameter,
){
  notice $parameter
}

require test
==
root@service1:/etc/puppet/connectdata# puppet apply test.pp
Notice: Scope(Class[Test]): {"type"=>"group", "filter"=>""} {"type"=>"passwd", "filter"=>""}
Error: requested unassigned attribute to_ary from {"type"=>"group", "filter"=>""} on node service1.private.worleyco.com
Error: requested unassigned attribute to_ary from {"type"=>"group", "filter"=>""} on node service1.private.worleyco.com

==
hash of hashes seems to work fine ( test::parameter = { "one" => hash_one, "two" => hash_two } ) yields
Notice: Scope(Class[Test]): {"one"=>{"type"=>"group", "filter"=>""}, "two"=>{"type"=>"passwd", "filter"=>""}}
==
trace and debug stack to follow
```

**Comment by joenuts1** [comment]
`root@service1:/etc/puppet/connectdata# puppet apply test.pp --debug --trace
Debug: Runtime environment: puppet_version=3.8.5, ruby_version=2.3.0, run_mode=user, default_encoding=ISO-8859-1
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Loading external facts from /var/lib/puppet/facts.d
Info: Loading facts
Debug: Loading facts from /etc/puppet/modules/puppi/lib/facter/puppi_projects.rb
Debug: Loading facts from /etc/puppet/modules/puppi/lib/facter/windows_common_appdata.rb
Debug: Loading facts from /etc/puppet/modules/puppi/lib/facter/last_run.rb
Info: Loading facts
Debug: Loading facts from /etc/puppet/modules/sudo/lib/facter/sudoversion.rb
Info: Loading facts
Debug: Loading facts from /etc/puppet/modules/apache/lib/facter/apache_version.rb
Info: Loading facts
Debug: Loading facts from /etc/puppet/modules/custom_facts/lib/facter/roles.rb
Info: Loading facts
Debug: Loading facts from /etc/puppet/modules/stdlib/lib/facter/service_provider.rb
Debug: Loading facts from /etc/puppet/modules/stdlib/lib/facter/pe_version.rb
Debug: Loading facts from /etc/puppet/modules/stdlib/lib/facter/root_home.rb
Debug: Loading facts from /etc/puppet/modules/stdlib/lib/facter/puppet_vardir.rb
Debug: Loading facts from /etc/puppet/modules/stdlib/lib/facter/facter_dot_d.rb
Debug: Loading facts from /etc/puppet/modules/stdlib/lib/facter/package_provider.rb
Info: Loading facts
Debug: Loading facts from /etc/puppet/modules/php/lib/facter/php_version.rb
Info: Loading facts
Debug: Loading facts from /etc/puppet/modules/apt/lib/facter/apt_reboot_required.rb
Debug: Loading facts from /etc/puppet/modules/apt/lib/facter/apt_updates.rb
Debug: Loading facts from /etc/puppet/modules/apt/lib/facter/apt_update_last_success.rb
Info: Loading facts
Debug: Loading facts from /var/lib/puppet/lib/facter/roles.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/service_provider.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/pe_version.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/root_home.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/apt_reboot_required.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/apt_updates.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/puppi_projects.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/apache_version.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/apt_update_last_success.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/puppet_vardir.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/facter_dot_d.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/sudoversion.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/php_version.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/package_provider.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/windows_common_appdata.rb
Debug: Loading facts from /var/lib/puppet/lib/facter/last_run.rb
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Puppet::Type::Service::ProviderDaemontools: file /usr/bin/svc does not exist
Debug: Puppet::Type::Service::ProviderRunit: file /usr/bin/sv does not exist
Debug: Puppet::Type::Service::ProviderUpstart: file /sbin/start does not exist
Debug: Puppet::Type::Service::ProviderLaunchd: file /bin/launchctl does not exist
Debug: Puppet::Type::Service::ProviderOpenrc: file /bin/rc-status does not exist
Debug: Puppet::Type::Service::ProviderGentoo: file /sbin/rc-update does not exist
Debug: Puppet::Type::Service::ProviderRedhat: file /sbin/chkconfig does not exist
Debug: Puppet::Type::Package::ProviderPecl: file pecl does not exist
Debug: Puppet::Type::Package::ProviderPear: file pear does not exist
Debug: Puppet::Type::Package::ProviderAix: file /usr/bin/lslpp does not exist
Debug: Puppet::Type::Package::ProviderOpenbsd: file pkg_info does not exist
Debug: Puppet::Type::Package::ProviderFreebsd: file /usr/sbin/pkg_info does not exist
Debug: Puppet::Type::Package::ProviderPorts: file /usr/local/sbin/portupgrade does not exist
Debug: Puppet::Type::Package::ProviderPortage: file /usr/bin/emerge does not exist
Debug: Puppet::Type::Package::ProviderSun: file /usr/bin/pkginfo does not exist
Debug: Puppet::Type::Package::ProviderNim: file /usr/sbin/nimclient does not exist
Debug: Puppet::Type::Package::ProviderSunfreeware: file pkg-get does not exist
Debug: Puppet::Type::Package::ProviderFink: file /sw/bin/fink does not exist
Debug: Puppet::Type::Package::ProviderRpm: file rpm does not exist
Debug: Puppet::Type::Package::ProviderUrpmi: file urpmi does not exist
Debug: Puppet::Type::Package::ProviderAptrpm: file rpm does not exist
Debug: Puppet::Type::Package::ProviderRug: file /usr/bin/rug does not exist
Debug: Puppet::Type::Package::ProviderZypper: file /usr/bin/zypper does not exist
Debug: Puppet::Type::Package::ProviderYum: file yum does not exist
Debug: Puppet::Type::Package::ProviderPkgin: file pkgin does not exist
Debug: Puppet::Type::Package::ProviderHpux: file /usr/sbin/swinstall does not exist
Debug: Puppet::Type::Package::ProviderOpkg: file opkg does not exist
Debug: Puppet::Type::Package::ProviderPkg: file /usr/bin/pkg does not exist
Debug: Puppet::Type::Package::ProviderAptitude: file /usr/bin/aptitude does not exist
Debug: Puppet::Type::Package::ProviderUp2date: file /usr/sbin/up2date-nox does not exist
Debug: Puppet::Type::Package::ProviderPortupgrade: file /usr/local/sbin/portupgrade does not exist
Debug: Puppet::Type::Package::ProviderPacman: file /usr/bin/pacman does not exist
Debug: /Package[dummy]: Provider apt does not support features virtual_packages; not managing attribute allow_virtual
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: hiera(): CONNECT: Backend initialized
Debug: hiera(): CONNECT: datadir is set to /etc/puppet/connectdata
Debug: hiera(): CONNECT: parsing Connect config file /etc/puppet/connectdata/common.config.
Debug: hiera(): CONNECT: Assign {"type"=>"group", "filter"=>""} to hash_one.
Debug: hiera(): CONNECT: Assign {"type"=>"passwd", "filter"=>""} to hash_two.
Debug: hiera(): CONNECT: Assign [#<Connect::Entry::Reference:0x000000030c6748 @xref=[#<struct Connect::Xref file_name="/etc/puppet/connectdata/common.config", lineno=20>], @value="hash_one", @selector=nil>, #<Connect::Entry::Reference:0x000000030c6068 @xref=[#<struct Connect::Xref file_name="/etc/puppet/connectdata/common.config", lineno=22>], @value="hash_two", @selector=nil>] to test::parameter.
Debug: hiera(): Cannot find datafile /etc/puppet/connectdata/locations/hammond.config, skipping
Debug: hiera(): Cannot find datafile /etc/puppet/connectdata/zones/private.config, skipping
Debug: hiera(): Cannot find datafile /etc/puppet/connectdata/environments/production.config, skipping
Debug: hiera(): Cannot find datafile /etc/puppet/connectdata/roles/undefined_workstation.config, skipping
Debug: hiera(): Cannot find datafile /etc/puppet/connectdata/nodes/service1.private.worleyco.com.config, skipping
Debug: hiera(): CONNECT: looked up 'test::parameter' found '[{"type"=>"group", "filter"=>""}, {"type"=>"passwd", "filter"=>""}]'
Notice: Scope(Class[Test]): {"type"=>"group", "filter"=>""} {"type"=>"passwd", "filter"=>""}
Error: requested unassigned attribute to_ary from {"type"=>"group", "filter"=>""} on node service1.private.worleyco.com
/etc/puppet/modules/connect/lib/method_hash.rb:14:in `method_missing'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:440:in `flatten'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:440:in `block in copy_as_resource'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:435:in `each'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:435:in `copy_as_resource'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:516:in `block in to_catalog'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:512:in `each'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:512:in `to_catalog'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:409:in `to_resource'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:34:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:148:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/lib/ruby/vendor_ruby/puppet.rb:246:in `override'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:121:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:34:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:95:in `block (2 levels) in compile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:93:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:161:in `block in benchmark'
/usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:92:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:52:in `find'
/usr/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:222:in `block in main'
/usr/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/lib/ruby/vendor_ruby/puppet.rb:246:in `override'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:198:in `main'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:159:in `run_command'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:507:in `plugin_hook'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:496:in `exit_on_fail'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:146:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:92:in `execute'
/usr/bin/puppet:8:in `<main>'
Error: requested unassigned attribute to_ary from {"type"=>"group", "filter"=>""} on node service1.private.worleyco.com
/etc/puppet/modules/connect/lib/method_hash.rb:14:in `method_missing'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:440:in `flatten'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:440:in `block in copy_as_resource'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:435:in `each'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:435:in `copy_as_resource'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:516:in `block in to_catalog'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:512:in `each'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:512:in `to_catalog'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:409:in `to_resource'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:34:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:148:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/lib/ruby/vendor_ruby/puppet.rb:246:in `override'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:121:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:34:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:95:in `block (2 levels) in compile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:93:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:161:in `block in benchmark'
/usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:92:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:52:in `find'
/usr/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:222:in `block in main'
/usr/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/lib/ruby/vendor_ruby/puppet.rb:246:in `override'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:198:in `main'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:159:in `run_command'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:507:in `plugin_hook'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:496:in `exit_on_fail'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:146:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:92:in `execute'
/usr/bin/puppet:8:in `<main>'
`

**Comment by hajee** [comment]
Can you conform this fix?

**Comment by joenuts1** [comment]
Confirmed fixed. Sorry to trouble you for such simple fixes. I guess I need to learn ruby one day!
And again, thanks for the quick solution.

**Comment by hajee** [comment]
No problem. And to make you feel better: this is not a simple fix. This is deep inside the nitty gritty details of `connect`  and `ruby`.
