### ISSUE TITLE
Feature Request: Using object types as variables

### ISSUE THREAD

**Issue by synotio** [enterprisemodules/connect#9]
I'm trying to do something like this:

```
# prd_db_server.config
include 'customers/*'

# dev_db_server.config
include 'customers/*'

# customers/customer1.config
customers::customer1::username = "user1"

dev_db('customer1') {
       username => customers::customer1::username,
       password => "blah"
}

prd_db('customer1') {
       username => customers::customer1::username,
       password => "blah"
}

# customers/customer2.config
customers::customer2::username = "user2"

dev_db('customer2') {
       username => customers::customer1::username,
       password => "blah"
}

prd_db('customer2') {
       username => customers::customer1::username,
       password => "blah"
}
```

Currently, the first two files needs to look like this in order for anything to happen:

```
# prd_db_server.config
include 'customers/*'

prd_db = {
    prd_db('customer1'),
    prd_db('customer2')
}

# dev_db_server.config
include 'customers/*'

dev_db = {
    dev_db('customer1'),
    dev_db('customer2')
}
```

This means that as the amount of data in the customers folder grow, the server configs also get larger as they need to reference every object of that type.

If connect could automatically merge all objects created as a certain type at the end of the parse process, all those huge object arrays can be removed since they will be generated automatically. This will however mean that the object type name will be a reserved keyword. I suppose it's possible to check if the user has defined a variable with that name as well before doing anything.

If there's better ways of doing this with the current version, please let me know.

**Comment by hajee** [comment]
I'm trying to understand, but actually do  not yet. Can you try explain from the puppet side what you would like to have?

**Comment by synotio** [comment]
From the puppet side, I'm trying to do this:

```
node 'dev_db_server' {
    $databases = hiera('dev_db', {})
    create_resources('mysql::db', $databases)
}

node 'prd_db_server' {
    $databases = hiera('prd_db', {})
    create_resources('mysql::db', $databases)
}
```

The effect is that adding a new customer file automatically creates the relevant dev/prd databases without changing anything else.

**Comment by hajee** [comment]
Would something like this work in your use case?

```
any_variable = prd_db('customer%') 
```

The rule would be if the identifier for the object contains a wildcard, it would return a hash of all objects that can be used in a `create_resources`  statement. It would also be easy to explain and I think we can fit this in the current syntax.

**Comment by synotio** [comment]
That would be absolutely perfect. It's more flexible than my suggestion as well.

**Comment by hajee** [comment]
Are you using connect with hiera5?

**Comment by synotio** [comment]
Nope, 1.3.4 to be more exact. But I can upgrade if needed,

**Comment by hajee** [comment]
What is your use case for the relatively old version?

**Comment by synotio** [comment]
It happened to be the one bundled with EPEL on CentOS 7 :)

**Comment by hajee** [comment]
Ah. I see. 

I will see if I can make some time in somewhere in the the current or next week to look at the feature. Is that ok?

**Comment by synotio** [comment]
That'd be awesome! Thanks!

**Comment by hajee** [comment]
Commit 298a2e1c83615a52fab1d8a7198e7936bdb5085e implements this. Can you check this out?

**Comment by synotio** [comment]
Wow, awesome! That was exactly what i was looking for. Thanks!

I found what looks like a minor bug when using a regex that matches everything, the following code demonstrates it:

```
foo("a1") { value: 'a1' }
foo("a2") { value: 'a2' }
foo("a3") { value: 'a3' }

bar = foo(/.*/)
baz = foo(/a./)
```

Output:
```
bar = {/.*/=>{}, /a./=>{}, "a1"=>{"value"=>"a1"}, "a2"=>{"value"=>"a2"}, "a3"=>{"value"=>"a3"}}
baz = {"a1"=>{"value"=>"a1"}, "a2"=>{"value"=>"a2"}, "a3"=>{"value"=>"a3"}}
```

Easiest workaround is to use something like `bar = foo(/[0-9A-Za-z].*/)`

**Comment by hajee** [comment]
Commit 62d65103f7a4609f96841068f64763ea2badfc66 should fix this too. Again, can you validate this?

**Comment by synotio** [comment]
Yep, works fine!
